config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # resources :users
    resources :foods, except: [:edit, :update]
    resources :recipes, only: [:index, :show, :new, :create, :destroy] do 
      resources :recipe_foods, only: [:new, :create, :destroy]
    end
    
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/general_shopping_list', to: 'foods#general'
  get '/public_recipes', to: 'recipes#public'
  # Defines the root path route ("/")
  root "foods#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 1 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :preparation_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :cooking_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy

  validates :name, presence: true
  validates :email, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def after_sign_in_path_for(_resource)
    foods_path
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @foods = Food.all
  end

  def new
    @food = Food.new
  end

  def create
    food = current_user.foods.new(food_params)
    respond_to do |format|
      format.html do
        if food.save
          flash[:notice] = 'Food was saved successfully.'
          redirect_to foods_path
        else
          flash.now[:alert] = 'There was an error Creating the food. Please try again.'
          render :new
        end
      end
    end
  end

  def general
    @foods = current_user.foods
    current_user.recipes.map do |recipe|
      recipe.recipe_foods.map do |recipe_food|
        food = recipe_food.food
        test = @foods.select { |f| f.name == food.name }[0]
        test.quantity = test.quantity - recipe_food.quantity
      end
    end
    @foods = @foods.select { |f| f.quantity.negative? }
    @foods.each { |f| f.quantity *= -1 }
    @total = 0
    @foods.each do |food|
      @total += (food.price * food.quantity)
    end
  end

  def destroy
    @food = Food.find(params[:id])
    if @food.destroy
      flash[:notice] = 'Food was deleted successfully.'
    else
      flash.now[:alert] = 'There was an error deleting the food.'
    end
    redirect_to foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :quantity, :measurement_unit, :price)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include HomeHelper

  def index
    # implement
  end

  def public_recipes
    @recipes = Recipe.includes([:user]).where(public: true)
  end

  def shopping_list
    authenticate_user!

    @items, @total = calculate_shopping
    authorize! :read, current_user
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    unless @recipe.user == current_user
      flash[:alert] = 'You can only add foods to your own recipes.'
      redirect_to recipe_path(@recipe)
    end
    @recipe_food = RecipeFood.new
    @foods = current_user.foods
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe = @recipe
    if @recipe_food.save
      flash[:notice] = 'Food added to recipe.'
      redirect_to recipe_path(@recipe)
    else
      flash[:alert] = 'Food not added to recipe.'
      render :new
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = @recipe_food.recipe
    if @recipe_food.destroy
      flash[:notice] = 'Food removed from recipe.'
    else
      flash[:alert] = 'Food not removed from recipe.'
    end
    redirect_to recipe_path(@recipe)
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def public
    @totals = {}
    @public_recipes = Recipe.where(public: true).order('created_at DESC')
    @public_recipes.each do |pub|
      total = 0
      RecipeFood.where(recipe_id: pub.id).each do |rec_food|
        total += rec_food.quantity * rec_food.food.price
      end
      @totals[pub.name] = total
    end
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      flash[:notice] = 'Recipe was saved successfully.'
      redirect_to recipes_path
    else
      flash.now[:alert] = 'There was an error creating the recipe. Please try again.'
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if @recipe.destroy
      flash[:notice] = 'Recipe was deleted successfully.'
    else
      flash.now[:alert] = 'There was an error deleting the recipe.'
    end
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :cooking_time, :preparation_time, :description, :public)
  end
end

app/controllers/turbo_controller.rb
class TurboController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      raise e if get?

      if has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @current_user = current_user
  end

  def sign_out
    sign_out_and_redirect(current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def calculate_needs
    list = current_user.recipes.includes(%i[recipe_foods])
    needs = Hash.new { |k, v| k[v] = 0 }
    list.each do |recipe|
      ingredients = recipe.recipe_foods.pluck(:food_id, :quantity).group_by(&:shift).transform_values(&:flatten)
      ingredients.each { |k, v| needs[k] += v[0] }
    end
    needs
  end

  def calculate_shopping
    needs = calculate_needs
    list = current_user.foods.pluck(:id, :name, :price, :quantity,
                                    :measurement_unit).group_by(&:shift).transform_values(&:flatten)

    items = []
    total = 0
    needs.each do |id, v|
      name, unitp, qty, measurement_unit = list[id]
      quantity = v - qty
      next unless quantity.positive?

      price = quantity * unitp
      total += price
      items << Food.new(name:, quantity:, price:, measurement_unit:)
    end
    [items, total]
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_food_helper.rb
module RecipesFoodHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/foods/general.html.erb
<div class="nice">
    <h3 class="heading">Shopping List</h3>
    <div class="awesome">
      <div class='rest'>
      <span>Amount of food items to buy: </span>
      <span>&nbsp;<%= @foods.length %></span>
      </div>

      <div class='rest'>
      <span>Total value of food needed:</span>
      <span>&nbsp;<%= @total %></span>
      </div>
    </div>

    <table class="table">
      <thead>
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Price</th>
          <th>Value</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <tr>
            <td><%= food.name %></td>
             <td><%= food.quantity %></td>
            <td><%= food.measurement_unit %></td>
            <td>$<%= food.price %></td>
            <td><%= button_to "Delete", food_path(food.id), data: {turbo_method: :delete, turbo_confirm: 'are you sure'}, method: :delete %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

app/views/foods/index.html.erb
<section class='food-section'> 
  <h1 class="heading"> All Foods</h1>

  <div class="btn-div">
    <%= link_to "Add food", new_food_path, class:"btn-add" %>
  </div>

<div class="listDiv">
   <table class="table tab">
    <thead>
        <tr>
        <th >Food</th>
        <th >Quantity</th>
        <th>Measurement_Unit</th>
        <th>Unit Price</th>
        <th>Action</th>
        </tr>
    </thead>

    <tbody>
    <% @foods.each do |food|%>
    <tr>
      <td><%= food.name%></th>
      <td><%= food.quantity%></th>
      <td><%= food.measurement_unit%></td>
      <td>$<%= food.price%></td>
      <td>
      <%if current_user == food.user%>
        <%=link_to "Delete", food_path(food.id), data: { turbo_method: :delete,turbo_confirm: "Are you sure?"}, class:"btn-delete"%>
      <%end%>
      </td>
    </tr>
    <% end %>
    </tbody>
</table>
</div>
</section>

app/views/foods/new.html.erb
<h2 class="heading">Add Food</h2>
<div class='formed'>
<%= form_with  model: @food, class:"input-form"  do |f|%>
    <div class="form-div" >
    <div>
    <%= f.label :name%><br>
    <%= f.text_field :name, class:"form-control",  required: true, id:"name"%><br>
    </div>

    <div>
    <%= f.label :quantity%><br>
    <%= f.number_field :quantity, class:"form-control",  required: true, id:"quantity"%><br>
    </div>

    <div>
    <%= f.label :measurement_unit %><br>
    <%= f.text_field :measurement_unit,  class:"form-control" , required: true, id:"measurement"%><br>
    </div>

    <div>
    <%= f.label :price, class:"form-label" %><br>
    <%= f.number_field :price ,  class:"form-control" , required: true, id:"price"%><br>
    </div>

    </div>
    <div>
    <%= f.submit "Create Food", class:"btn-create" %>
    </div>
 <% end %>
<div class="form-div" >
  <div>
      <%=link_to 'Back', foods_path, class:"btn-back"%>
  </div>
</div>

app/views/foods/show.html.erb
<h1><%= @recipe.name %></h1>
<div class="column col-center width-60 gap-1">
  <div class="row row-justify">
    <div class="column">
      <h2>Preparation Time: <%= @recipe.preparation_time %></h2>
      <h2>Cooking Time: <%= @recipe.cooking_time %></h2>
    </div>
    <div>
      <h3>Public<h3>
      <label class="switch">
        <input type="checkbox" <% if @recipe.public %>checked<% end %> disabled>
        <span class="slider round"></span>
      </label>
    </div>
  </div>

  <p><%= @recipe.description %></p>
  
  <div class="row row-justify">
    <%=link_to shopping_list_path, :class => 'btn' do%>
      <h4>Generate shopping list</h4>
    <%end%>
    <% if can? :create, @recipe %>
      <%= link_to new_recipe_recipe_food_path(@recipe.id), class: "btn" do %>
        <h4>Add new ingredient</h4>
      <%end%>
    <% end %>
  </div>

  <table class="width-100">
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% if @recipe_foods.empty? %>
      <tr><td colspan="4">The food list is empty</td></tr>
      <% else %>
        <% @recipe_foods.each do |recipe_food| %>
          <tr>    
            <td><%= recipe_food.food.name %></td>
            <td><%= recipe_food.quantity %></td>
            <td><%= recipe_food.food.price %></td>
            <td>
              <% if can? :update, recipe_food.recipe %>
                <%=link_to "Modify", edit_recipe_recipe_food_path(@recipe, recipe_food) %>
              <% end %>
              <% if can? :destroy, recipe_food.recipe %>
                <%= link_to "Remove", recipe_recipe_food_path(recipe_food.recipe_id, recipe_food.food_id), data: { turbo_method: :delete } %>
              <% end %>
            </td>
          </tr>
        <%end%>
      <% end %>
    </tbody>
  </table>
  <p></p>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <div class='nav-link'>
    <%= form_with url: root_path, method: :get do %>
      <button class='logo'>LazyFood</button>
    <% end %>
    <% if current_user%>
      <%= form_with url: foods_path, method: :get do %>
        <button class='list'>Foods</button>|
      <% end %>
      <%= form_with url: recipes_path, method: :get do %>
        <button class='list'>Recipes</button> |
      <% end %>
      <%= form_with url: public_recipes_path, method: :get do %>
        <button class='list'>Public Recipes</button>|
      <% end %>
      <%= form_with url:general_shopping_list_path, method: :get do %>
        <button class='list'>General Shopping List</button>
      <% end %>
    <% end %>
  </div>
  <div class='nav-list'>
    <% unless current_user%>
    <%= form_with model: User.new, url: new_user_session_path, method: :get, class:'log' do %>
      <button> Sign in</button>
    <% end %>
    <%= form_with model: User.new, url: new_user_registration_path, method: :get, class:'log' do %>
      <button>Sign up</button>
    <% end %>
  <% end %>
  <% if current_user %>
    <%=form_with model: User.new, url: destroy_user_session_path, data: { turbo_method: :delete },
class:'sign-out' do %> 
      <button>Sign out</button>
    <% end %>
    <span class='alert'>
     <p>Welcome <%= current_user.name%></p>
    </span>
  <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <header>
    <%= render "layouts/navbar"%>
  </header>
    <%= yield %>
  </body>
</html>

app/views/recipe_foods/new.html.erb
<h2 class="heading">Add Recipe Food</h2>
<div class='add-ing'>
<%= form_with url: recipe_recipe_foods_path, scope: :recipe_food do |f| %>
    <div class='new-label'>
    <%= f.label :food %><br>
    <%= f.select :food_id, current_user.foods.collect {|food| [food.name, food.id]}%>
    </div>

    <div class='new-label'>
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity, required: true, placeholder: '1',  min: 1 %>
    </div>

    <div class='new-label'>
    <%= f.submit "Create Recipe_Food" %>
    </div>
<% end %>
  <div class='go-back'>
    <%=link_to 'Back', foods_path %>
  </div>
</div>

app/views/recipes/index.html.erb
<div class='recipe'> 
<button class='get'><%= link_to "Add Recipe", new_recipe_path %></button>
<div class='done'>
<% @recipes.each do |recipe| %>
  <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
  <p><%= recipe.description %></p>
  <%= button_to "Delete", recipe_path(recipe.id),data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, method: :delete, class: "delete" %>
<% end %>
</div>
</div>

app/views/recipes/new.html.erb
<div class="form-recipe">
  <%= form_with model: @recipe do |form| %>
    <% if @recipe.errors.any? %>
      <div class='form-list'>
        <h3><%= pluralize(@recipe.errors.count, "error") %> occurred: </h3>
        <ul>
          <%= @recipe.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <h2>New Recipe</h2>
    <div class='holder'>
    <div class='form-set'>
      <%= form.label :name, "Name" %>
      <%= form.text_field :name, required: true, autofocus: true %>
    </div>
    <div class='form-set'>
      <%= form.label :preparation_time, "Preparation Time" %>
      <%= form.number_field :preparation_time, required: true, autofocus: true %>
    </div>
    <div class='form-set'>
      <%= form.label :cooking_time, "Cooking Time" %>
      <%= form.number_field :cooking_time, required: true, autofocus: true %>
    </div>
    <div class='form-set'>
      <%= form.label :description, "Description" %>
      <%= form.text_area :description, required: true, autofocus: true %>
    </div>
     </div>
    <div class='adding'> 
    <div>
      <%= form.label :public%>
      <%= form.check_box :public%>
    </div>
    <div class='btn'>
      <%= form.submit 'Create Recipe'%>
    </div>
    </div>
  <% end %>
</div>

app/views/recipes/public.html.erb
<div class="total">
    <h3 class="heading">Public Recipes</h3>
    <ul class="state">
      <% @public_recipes.each do |recipe| %>
        <li class="link">
          <div class="play">
            <div>
              <%= link_to recipe.name, recipe_path(recipe) %>
            </div>
            <span>By: <%= recipe.user.name %></span>
          </div>
          <div class="play">
            <div>
              <span>Total food items: </span>
              <span><%= recipe.foods.length %></span>
            </div>
            <div class="play">
              <span>Total price:</span>
              <% if recipe.recipe_foods.find_by(recipe_id: recipe.id) %>
                    <span><%= recipe.recipe_foods.find_by(recipe_id: recipe.id).quantity * recipe.recipe_foods.find_by(recipe_id: recipe.id).food.price %></span>
              <% else %>
                <span>0</span>
              <% end %>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>

app/views/recipes/show.html.erb
<div class="recipe-detail">
<h2><%= @recipe.name %></h2>
<div>
<div class="details">
    <div class="form-check">
      <% if @recipe.public == false %>
        <%= check_box :public, checked: false  %>
        <label class="check-label" for="unchecked">Public</label>
      <% else %>
        <%= check_box :public, checked: true %>
        <label class="check-label" for="checked">Public</label>
      <%end%>
    </div>

  <div class="time">
    <p>Preparation time: </p>
    <span><%=@recipe.preparation_time %></span>
  </div>
  <div class="time">
    <p>Cooking time: </p>
    <span><%=@recipe.cooking_time %></span>
  </div>

  <div class='res'>
    <p><%= @recipe.description %></p>
  </div>

  <div class="shop-list">
    <div class="check-list">
      <%= link_to 'Generate shopping list', general_shopping_list_path %>
    </div>
     <div class="check-list">
      <%= link_to 'Add ingredient', new_recipe_recipe_food_path(@recipe) %>
    </div>
  </div>
  <hr>
</div>


<table class='table'>
 <% if @recipe.recipe_foods.any? %>
    <thead>
        <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <th>Action</th>
        </tr>
    </thead>
    <tbody>
    <% @recipe.recipe_foods.each do |food|%>
    <tr>
      <td><%= food.food.name%></th>
      <td><%= food.quantity%></td>
      <td><%= food.quantity * food.food.price %></td>
      <td>
        <%=link_to "Delete", recipe_recipe_food_path(@recipe, food), data: {turbo_method: :delete, turbo_confirm: 'are you sure'}, method: :delete%>
      </td>
    </tr>
    <%end%>
    </tbody>
  <%end%>
</table>
</div>

app/views/recipes_foods/edit.html.erb
<h2>Edit quantity of: <%= @recipe_food.food.name %>

<%= form_with model: @recipe_food, url: recipe_recipe_food_path, method: :patch do |form| %>
  <%= form.label :quantity %>
  <%= form.number_field :quantity %>
  <%= form.submit "Update" %>
<% end %>

app/views/recipes_foods/update.html.erb
<h1>RecipeFoods#update</h1>
<p>Find me in app/views/recipe_foods/update.html.erb</p>

app/views/users/index.html.erb
<% if user_signed_in? %>
  <p class='alert'>Welcome <%= current_user.name%></p>
<% end %>